[package]
name = "eve-types-builder"
version = "0.1.0"
edition = "2021"

[dependencies]
zip = "2.2.1"
serde = { version = "1.0.215", features = ["derive"] }
serde_yaml = "0.9.34+deprecated"
serde_json = "1.0.133"
flate2 = "1.0.35"